Add support for the x64 platform in wixproj templates
wixtoolset/VisualStudioExtension pull request #17
Opened 2020-04-10 09:53 UTC by lb90

This is just a proposal...

Currently the wixproj templates only support the x86 platform. It's easy to add support for the x64 platform by manual editing, but having out of the box support for that would be great.

I'm not sure if something can be done better

2020-04-10 09:54 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/wixtoolset/VisualStudioExtension?pullRequest=17) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/wixtoolset/VisualStudioExtension?pullRequest=17) before we can accept your contribution.<br/><br/>:x: lb90 [sign now](https://cla.dotnetfoundation.org/wixtoolset/VisualStudioExtension?pullRequest=17)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/wixtoolset/VisualStudioExtension?pullRequest=17) it.</sub>

2020-05-20 01:07 UTC, rseanhall requested changes
Thanks. This seems to be the right way to do this.

2020-05-20 01:07 UTC, rseanhall commented on src/Templates/v3/Projects/CustomActionCPP/CustomAction.vcxproj
> +			<AdditionalLibraryDirectories>$(WIX)sdk\$(WixPlatformToolset)\lib\x86;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
This needs to be x64.

2020-05-20 01:07 UTC, rseanhall commented on src/Templates/v3/Projects/CustomActionCPP/CustomAction.vcxproj
> +			<AdditionalLibraryDirectories>$(WIX)sdk\$(WixPlatformToolset)\lib\x86;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
This needs to be x64.

2020-06-21 09:38 UTC, lb90 commented on src/Templates/v3/Projects/CustomActionCPP/CustomAction.vcxproj
> +			<AdditionalLibraryDirectories>$(WIX)sdk\$(WixPlatformToolset)\lib\x86;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
Good catch! Fixed.

2020-06-21 09:38 UTC, lb90 commented on src/Templates/v3/Projects/CustomActionCPP/CustomAction.vcxproj
> +			<AdditionalLibraryDirectories>$(WIX)sdk\$(WixPlatformToolset)\lib\x86;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
Fixed

2020-06-27 13:13 UTC, lb90 commented
Added more project templates, should be complete by now.

Also added a .wxi include file to the MSI Project template. This is to help with installing in either ProgramFilesFolder or ProgramFiles64Folder, depending on the active Platform configuration. It contains a simple 'PlatformProgramFilesFolder' define. That include file is named 'Platform.wxi', but perhaps we could change the name to 'TargetArch.wxi' or 'TargetPlatform.wxi', any suggestion about naming is welcome.

2020-06-28 04:27 UTC, rseanhall commented on src/Templates/v3/Projects/WixBundleProject/BundleProject.wixproj
> +		<IntermediateOutputPath>obj\$(Platform)\$(Configuration)\</IntermediateOutputPath>
Bundles are always x86 in v3, so I don't think we should add an x64 configuration.

2020-06-28 04:27 UTC, rseanhall commented on src/Templates/v3/Projects/WixLibrary/setuplibrary.wixproj
> +		<IntermediateOutputPath>obj\$(Platform)\$(Configuration)\</IntermediateOutputPath>
I don't think library projects should have multiple platforms. Best practice is to build one .wixlib with all the architectures, with different `Id`s based on the target architecture.

2020-06-28 04:27 UTC, rseanhall commented on src/Templates/v3/Projects/WixProject/Product.wxs
> +			<Directory Id="$(var.PlatformProgramFilesFolder)">
I don't think we should do this. You shouldn't build the project as x86 and as x64 and then distribute them both. You would need to vary other things as well, such as the UpgradeCode.

2020-06-28 04:27 UTC, rseanhall commented on src/Templates/v4/Projects/WixBundleProject/BundleProject.wixproj
> +		<IntermediateOutputPath>obj\$(Platform)\$(Configuration)\</IntermediateOutputPath>
I don't want to touch any of the v4 templates. The projects will look completely different.

2021-12-25 04:50 UTC, AraHaan commented
What about arm64 to the templates as well?

2021-12-26 15:41 UTC, robmen commented
Interesting proposal. Feel free to send a completed solution in the future. For now, closing the stale PR.

2021-12-26 15:41 UTC, closed without merging